server:
  port: 9191

spring:
  application:
    name: NACOS-COMMONS #微服务服务名
  cloud:
    nacos:
      server-addr: 1.117.47.7:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr} #作为nacos client 注册地址
        service: ${spring.application.name} #nacos server 注册服务名称